


=pod

=head1 NAME

unicruft - Approximating UTF-8 transliteration & recoding



=head1 SYNOPSIS

unicruft [OPTIONS] FILE(s)

 Arguments:
    FILE(s)  Input text file(s)

 Options
    -h      --help                 Print help and exit.
    -V      --version              Print version and exit.
    -mMODE  --mode=MODE            Conversion mode (lu|ua|ul|ud|uL|uD|uDpp)
    -u      --latin1-to-utf8       Convert Latin-1 to UTF-8
    -a      --utf8-to-ascii        Convert UTF-8 to ASCII (default)
    -l      --utf8-to-latin1       Convert UTF-8 to Latin-1
    -d      --utf8-to-latin1-de    Convert UTF-8 to Latin-1/DE
    -L      --utf8-to-utf8-latin1  Convert UTF-8 to UTF-8/Latin-1
    -D      --utf8-to-utf8-de      Convert UTF-8 to UTF-8/DE
    -P      --utf8-to-utf8-de-pp   (debug) run only the UTF-8/DE preprocessor
    -oFILE  --output=FILE          Output file (default=stdout).

=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

Approximating UTF-8 transliteration & recoding



=cut

###############################################################
# Arguments
###############################################################
=pod

=head1 ARGUMENTS

=over 4

=item C<FILE(s)>

Input text file(s)


If unspecified, standard input will be read.


=back



=cut


###############################################################
# Options
###############################################################
=pod

=head1 OPTIONS

=over 4

=item C<--help> , C<-h>

Print help and exit.

Default: '0'




=item C<--version> , C<-V>

Print version and exit.

Default: '0'




=item C<--mode=MODE> , C<-mMODE>

Conversion mode (lu|ua|ul|ud|uL|uD|uDpp)

Default: 'ua'


The C<--mode> argument is used to specify the requested conversion mode,
i.e. input and output encoding and character-(sub-)set.  Each supported
conversion mode has a long option alias as well as a canonical string value
for the C<--mode> argument.  See the documentation of the remaining conversion
options for details on the supported conversion modes.





=item C<--latin1-to-utf8> , C<-u>

Convert Latin-1 to UTF-8

Default: '0'


Equivalent to C<--mode=lu>.

Converts arbitrary 8-bit Latin-1 input to UTF-8.





=item C<--utf8-to-ascii> , C<-a>

Convert UTF-8 to ASCII (default)

Default: '0'


Equivalent to C<--mode=ua>.

Converts arbitrary UTF-8 input to a 7-bit ASCII approximation
using a modified version of the transliteration tables distributed
with the L<Text::Unidecode(3pm)|Text::Unidecode> perl module by Sean M. Burke.
This is the default conversion mode.





=item C<--utf8-to-latin1> , C<-l>

Convert UTF-8 to Latin-1

Default: '0'


Equivalent to C<--mode=ul>.

Converts arbitrary UTF-8 input to an 8-bit ISO-8859-1 (Latin-1) approximation.
Input characters in the Unicode Latin-1 supplement are identity-mapped
onto the 8-bit Latin-1 character set, other input characters are transliterated
as for the L<--utf8-to-ascii|/"--utf8-to-ascii , -a"> mode.





=item C<--utf8-to-latin1-de> , C<-d>

Convert UTF-8 to Latin-1/DE

Default: '0'


Equivalent to C<--mode=ud>.

Converts arbitrary UTF-8 input to an 8-bit ISO-8859-1 (Latin-1) approximation using only characters
active in contemporary German orthography.  Performs some
context-sensitive replacements (e.g. of combining I<Umlaute> and superscript letters),
and otherwise transliterates as for the L<--utf8-to-latin1|/"--utf8-to-latin1 , -l">
mode.





=item C<--utf8-to-utf8-latin1> , C<-L>

Convert UTF-8 to UTF-8/Latin-1

Default: '0'


Equivalent to C<--mode=uL>.

Just like L<--utf8-to-latin1|/"--utf8-to-latin1 , -l"> mode,
but output is encoded in UTF-8 which is guaranteed to contain only Unicode
characters in the range U+0000 .. U+00FF, i.e. the Latin-1 supplement.





=item C<--utf8-to-utf8-de> , C<-D>

Convert UTF-8 to UTF-8/DE

Default: '0'


Equivalent to C<--mode=uD>.

Just like L<--utf8-to-latin1-de|/"--utf8-to-latin1-de , -d"> mode,
but output is encoded in UTF-8 which is guaranteed to contain only Unicode
characters in the range U+0000 .. U+00FF, i.e. the Latin-1 supplement.





=item C<--utf8-to-utf8-de-pp> , C<-P>

(debug) run only the UTF-8/DE preprocessor

Default: '0'


Equivalent to C<--mode=uDpp>.

This mode performs only the preprocessing phase of the 
L<--utf8-to-utf8-de|/"--utf8-to-utf8-de , -D"> conversion.
Useful for debugging or complex processing pipelines.





=item C<--output=FILE> , C<-oFILE>

Output file (default=stdout).

Default: '-'




=back




=cut

###############################################################
# configuration files
###############################################################
=pod



=cut


###############################################################
# Addenda
###############################################################
=pod

=head1 ADDENDA



=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.07
using Getopt::Gen version 0.14.
Translation was initiated
as:

   optgen.perl -l --nocfile --nohfile --notimestamp --no-handle-rcfile -F unicruft unicruft.gog

=cut


###############################################################
# Bugs
###############################################################
=pod

=head1 BUGS AND LIMITATIONS



Too much copying in the underlying library makes things a tad slow.



=cut

###############################################################
# Footer
###############################################################
=pod

=head1 ACKNOWLEDGEMENTS

Perl by Larry Wall.

Getopt::Gen by Bryan Jurish.

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 SEE ALSO


Text::Unidecode(3pm),
recode(1),
iconv(1)


=cut


